### PR TITLE
Create Christmas Lights Profile

### PR DESCRIPTION
**Pull request by jvaglivelo**
Created a similar profile similar to animatedRainbowVertical instead with a set of red and green lights for Christmas.

### CODE REVIEW

**Comment by Codetector1374** [comment]
Please fix your style first.
https://ci.codetector.org/blue/organizations/jenkins/OpenAnnePro%2FAnnePro2-Shine/detail/PR-30/1/pipeline

**Comment by Codetector1374** [comment]
You can check style locally with `make clang-format`

**Review by Codetector1374 — CHANGES_REQUESTED** [review]
Style Changes Required. Make sure you can pass CI

**Review by DJSpace72 — COMMENTED** [review]
Ch

**Pull request closed without merging**
